/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Aluno
 */
public class InicialView extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialView
     */
    public InicialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuCadastrar = new javax.swing.JMenu();
        jmenuCadCurso = new javax.swing.JMenuItem();
        jMenuCadAluno = new javax.swing.JMenuItem();
        jMenuCadProfessor = new javax.swing.JMenuItem();
        jMenuCadDisciplina = new javax.swing.JMenuItem();
        jMenuCadTurma = new javax.swing.JMenuItem();
        jMenuConCurso = new javax.swing.JMenu();
        jMenuConCursp = new javax.swing.JMenuItem();
        jMenuConAluno = new javax.swing.JMenuItem();
        jMenuConProfessor = new javax.swing.JMenuItem();
        jMenuConDisciplina = new javax.swing.JMenuItem();
        jMenuConTurma = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sistemaAcademico.png"))); // NOI18N

        jmenuCadastrar.setText("Cadastrar");

        jmenuCadCurso.setText("Curso");
        jmenuCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCadCursoActionPerformed(evt);
            }
        });
        jmenuCadastrar.add(jmenuCadCurso);

        jMenuCadAluno.setText("Aluno");
        jMenuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadAlunoActionPerformed(evt);
            }
        });
        jmenuCadastrar.add(jMenuCadAluno);

        jMenuCadProfessor.setText("Professor");
        jMenuCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadProfessorActionPerformed(evt);
            }
        });
        jmenuCadastrar.add(jMenuCadProfessor);

        jMenuCadDisciplina.setText("Disciplina");
        jMenuCadDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadDisciplinaActionPerformed(evt);
            }
        });
        jmenuCadastrar.add(jMenuCadDisciplina);

        jMenuCadTurma.setText("Turma");
        jMenuCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadTurmaActionPerformed(evt);
            }
        });
        jmenuCadastrar.add(jMenuCadTurma);

        jMenuBar1.add(jmenuCadastrar);

        jMenuConCurso.setText("Consultar");

        jMenuConCursp.setText("Curso");
        jMenuConCursp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConCurspActionPerformed(evt);
            }
        });
        jMenuConCurso.add(jMenuConCursp);

        jMenuConAluno.setText("Aluno");
        jMenuConAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConAlunoActionPerformed(evt);
            }
        });
        jMenuConCurso.add(jMenuConAluno);

        jMenuConProfessor.setText("Professor");
        jMenuConProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConProfessorActionPerformed(evt);
            }
        });
        jMenuConCurso.add(jMenuConProfessor);

        jMenuConDisciplina.setText("Disciplina");
        jMenuConDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConDisciplinaActionPerformed(evt);
            }
        });
        jMenuConCurso.add(jMenuConDisciplina);

        jMenuConTurma.setText("Turma");
        jMenuConTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConTurmaActionPerformed(evt);
            }
        });
        jMenuConCurso.add(jMenuConTurma);

        jMenuBar1.add(jMenuConCurso);

        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadAlunoActionPerformed
        // TODO add your handling code here:
        AlunoCadastroView cadAluno = new AlunoCadastroView();
        cadAluno.setLocationRelativeTo(null);
        cadAluno.setVisible(true);
    }//GEN-LAST:event_jMenuCadAlunoActionPerformed

    private void jmenuCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCadCursoActionPerformed
        // TODO add your handling code here:
        CursoCadastroView cadCurso = new CursoCadastroView();
        cadCurso.setLocationRelativeTo(null);
        cadCurso.setVisible(true);
    }//GEN-LAST:event_jmenuCadCursoActionPerformed

    private void jMenuCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadProfessorActionPerformed
        // TODO add your handling code here:
        ProfessorCadastroView cadProf = new ProfessorCadastroView();
        cadProf.setLocationRelativeTo(null);
        cadProf.setVisible(true);      
    }//GEN-LAST:event_jMenuCadProfessorActionPerformed

    private void jMenuCadDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadDisciplinaActionPerformed
        // TODO add your handling code here:
        DisciplinaCadastroView cadDiscip = new DisciplinaCadastroView();
        cadDiscip.setLocationRelativeTo(null);
        cadDiscip.setVisible(true);
    }//GEN-LAST:event_jMenuCadDisciplinaActionPerformed

    private void jMenuCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadTurmaActionPerformed
        // TODO add your handling code here:
        TurmaCadastroView cadTurma = new TurmaCadastroView();
        cadTurma.setLocationRelativeTo(null);
        cadTurma.setVisible(true);
        
    }//GEN-LAST:event_jMenuCadTurmaActionPerformed

    private void jMenuConCurspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConCurspActionPerformed
        // TODO add your handling code here:
        CursoConsultarView conCurso = new CursoConsultarView();
        conCurso.setLocationRelativeTo(null);
        conCurso.setVisible(true);
    }//GEN-LAST:event_jMenuConCurspActionPerformed

    private void jMenuConAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConAlunoActionPerformed
        // TODO add your handling code here:
        AlunoConsultarView conAluno = new AlunoConsultarView();
        conAluno.setLocationRelativeTo(null);
        conAluno.setVisible(true);
    }//GEN-LAST:event_jMenuConAlunoActionPerformed

    private void jMenuConProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConProfessorActionPerformed
        // TODO add your handling code here:
        ProfessorConsultarView conProf = new ProfessorConsultarView();
        conProf.setLocationRelativeTo(null);
        conProf.setVisible(true);
    }//GEN-LAST:event_jMenuConProfessorActionPerformed

    private void jMenuConDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConDisciplinaActionPerformed
        // TODO add your handling code here:
        DisciplinaConsultaView conDisc = new DisciplinaConsultaView();
        conDisc.setLocationRelativeTo(null);
        conDisc.setVisible(true);
    }//GEN-LAST:event_jMenuConDisciplinaActionPerformed

    private void jMenuConTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConTurmaActionPerformed
        // TODO add your handling code here:
        TurmaConsultarView conTur = new TurmaConsultarView();
        conTur.setLocationRelativeTo(null);
        conTur.setVisible(true);
    }//GEN-LAST:event_jMenuConTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadAluno;
    private javax.swing.JMenuItem jMenuCadDisciplina;
    private javax.swing.JMenuItem jMenuCadProfessor;
    private javax.swing.JMenuItem jMenuCadTurma;
    private javax.swing.JMenuItem jMenuConAluno;
    private javax.swing.JMenu jMenuConCurso;
    private javax.swing.JMenuItem jMenuConCursp;
    private javax.swing.JMenuItem jMenuConDisciplina;
    private javax.swing.JMenuItem jMenuConProfessor;
    private javax.swing.JMenuItem jMenuConTurma;
    private javax.swing.JMenuItem jmenuCadCurso;
    private javax.swing.JMenu jmenuCadastrar;
    // End of variables declaration//GEN-END:variables
}
